=== sala223/FastBiz/FastBiz/conf/ds.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.fastbiz.com.cn/schema/ds" xmlns:jxb="http://java.sun.com/xml/ns/jaxb" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:ds="http://www.fastbiz.com.cn/schema/ds" elementFormDefault="qualified">
	<complexType name="datasource">
		<sequence>
			<element name="jndi-name" type="string" minOccurs="1" maxOccurs="1"></element>
			<element name="connection-url" type="string" minOccurs="1" maxOccurs="1"></element>
			<element name="user-name" type="string" minOccurs="0" maxOccurs="1"></element>
			<element name="password" type="string" minOccurs="0" maxOccurs="1"></element>
			<group ref="ds:pool-info" />
			<element name="property" type="ds:property" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="no-tx-datasource">
		<complexContent>
			<extension base="ds:datasource">
				<sequence>
					<element name="driver-class-name" type="string" minOccurs="1" maxOccurs="1"></element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="xa-datasource">
		<complexContent>
			<extension base="ds:datasource">
				<sequence>
					<element name="xa-datasource-class-name" type="string" minOccurs="1" maxOccurs="1"></element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="datasources">
		<sequence>
			<element name="no-tx-datasource" type="ds:no-tx-datasource"></element>
			<element name="xa-datasource" type="ds:xa-datasource"></element>
		</sequence>
	</complexType>

	<complexType name="property">
		<attribute name="property" type="string"></attribute>
		<attribute name="value" type="string"></attribute>
	</complexType>

	<simpleType name="transaction-isolation-level">
		<restriction base="string">
			<enumeration value="TRANSACTION_READ_UNCOMMITTED"></enumeration>
			<enumeration value="TRANSACTION_READ_COMMITTED"></enumeration>
			<enumeration value="TRANSACTION_REPEATABLE_READ"></enumeration>
			<enumeration value="TRANSACTION_SERIALIZABLE"></enumeration>
			<enumeration value="TRANSACTION_NONE"></enumeration>
		</restriction>
	</simpleType>

	<group name="pool-info">
		<sequence>
			<choice maxOccurs="unbounded">
				<element name="transaction-isolation" type="ds:transaction-isolation-level" minOccurs="0" maxOccurs="1"></element>
				<element name="min-pool-size" type="int" minOccurs="0" maxOccurs="1"></element>
				<element name="max-pool-size" type="int" minOccurs="0" maxOccurs="1"></element>
				<element name="initial-pool-size" type="int" minOccurs="0" maxOccurs="1"></element>
				<element name="acquire-retry-attempts" type="int" minOccurs="0" maxOccurs="1"></element>
				<element name="prepared-statement-cache-size" type="int" minOccurs="0" maxOccurs="1"></element>
				<element name="check-valid-connection-sql" type="string" minOccurs="0" maxOccurs="1"></element>
				<element name="valid-connection-checker-class-name" type="string" minOccurs="0" maxOccurs="1"></element>
				<element name="blocking-timeout-millis" type="int" minOccurs="0" maxOccurs="1"></element>
				<element name="max-idle-time" type="int" minOccurs="0" maxOccurs="1"></element>
			</choice>
		</sequence>
	</group>

	<element name="datasources" type="ds:datasources"></element>

</schema>

=== sala223/FastBiz/FastBiz/conf/ds.xml
<?xml version="1.0" encoding="UTF-8"?>
<datasources xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.fastbiz.com.cn/schema/ds"
	xsi:schemaLocation="http://www.fastbiz.com.cn/schema/ds http://www.fastbiz.com.cn/ds.xsd">
	<no-tx-datasource>
		<jndi-name>java:/comp/ds/test</jndi-name>
		<connection-url>jdbc:derby:fastbiz;</connection-url>
		<user-name></user-name>
		<password></password>
		<transaction-isolation>TRANSACTION_SERIALIZABLE</transaction-isolation>
		<min-pool-size>5</min-pool-size>
		<max-pool-size>100</max-pool-size>
		<initial-pool-size>3</initial-pool-size>
		<acquire-retry-attempts>10</acquire-retry-attempts>
		<prepared-statement-cache-size>180</prepared-statement-cache-size>
		<check-valid-connection-sql>SELECT 1</check-valid-connection-sql>
		<valid-connection-checker-class-name>com.mchange.v2.c3p0.impl.DefaultConnectionTester</valid-connection-checker-class-name>
		<blocking-timeout-millis>30000</blocking-timeout-millis>
		<max-idle-time>15</max-idle-time>
		<property property="p1" value="v1" />
		<property property="p2" value="v2" />
		<driver-class-name>org.apache.derby.jdbc.EmbeddedDriver</driver-class-name>
	</no-tx-datasource>
	<xa-datasource>
		<jndi-name>java:/comp/ds/xatest</jndi-name>
		<connection-url>jdbc:derby:fastbiz;</connection-url>
		<user-name>sa</user-name>
		<password>root</password>
		<transaction-isolation>TRANSACTION_SERIALIZABLE</transaction-isolation>
		<min-pool-size>5</min-pool-size>
		<max-pool-size>100</max-pool-size>
		<blocking-timeout-millis>5000</blocking-timeout-millis>
		<max-idle-time>15</max-idle-time>
		<property property="p1" value="v1" />
		<property property="p2" value="v2" />
		<xa-datasource-class-name>org.apache.derby.jdbc.ClientXADataSource</xa-datasource-class-name>
	</xa-datasource>
</datasources>
